---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html
namespace: infra
name: mecm_ops
version: 1.0.1
readme: README.md
authors:
  - Ansible Community
description: Ansible collection for Microsoft System Center Configuration Manager (MECM/SCCM/ConfigMgr) infrastructure operations and management
license_file: LICENSE
tags:
  - microsoft
  - mecm
  - sccm
  - configmgr
  - windows
  - infrastructure
  - operations
  - monitoring
repository: https://github.com/ansible-collections/infra.mecm_ops
# documentation: https://github.com/ansible-collections/infra.mecm_ops/tree/main/docs
homepage: https://github.com/ansible-collections/infra.mecm_ops
issues: https://github.com/ansible-collections/infra.mecm_ops/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - tests/integration/inventory.winrm
  - CLAUDE.md
  - .claude*

dependencies:
  microsoft.mecm: ">=1.0.0"
  ansible.windows: ">=1.0.0"
